hadd $1_all_mc_signal_barrel_QCDandInterference.root $1_all_mc_signal_barrel_WGJets.root $1_all_mc_signal_barrel_WGJJ_interference.root
hadd $1_all_mc_signal_endcap_QCDandInterference.root $1_all_mc_signal_endcap_WGJets.root $1_all_mc_signal_endcap_WGJJ_interference.root 
hadd $1_all_mc_control_barrel_QCDandInterference.root $1_all_mc_control_barrel_WGJets.root $1_all_mc_control_barrel_WGJJ_interference.root 
hadd $1_all_mc_control_endcap_QCDandInterference.root $1_all_mc_control_endcap_WGJets.root $1_all_mc_control_endcap_WGJJ_interference.root

hadd -f $1_all_mc_signal_barrel_qcd_ewk.root $1_all_mc_signal_barrel_WGJJ.root $1_all_mc_signal_barrel_WGJets.root
hadd -f $1_all_mc_signal_endcap_qcd_ewk.root $1_all_mc_signal_endcap_WGJJ.root $1_all_mc_signal_endcap_WGJets.root
hadd -f $1_all_mc_control_barrel_qcd_ewk.root $1_all_mc_control_barrel_WGJJ.root $1_all_mc_control_barrel_WGJets.root
hadd -f $1_all_mc_control_endcap_qcd_ewk.root $1_all_mc_control_endcap_WGJJ.root $1_all_mc_control_endcap_WGJets.root
hadd -f $1_all_mc_signal_barrel_other.root $1_all_mc_signal_barrel_WW.root $1_all_mc_signal_barrel_WZ.root $1_all_mc_signal_barrel_ZZ.root $1_all_mc_signal_barrel_ST_*.root $1_all_mc_signal_barrel_TTG.root $1_all_mc_signal_barrel_ZG.root
hadd -f $1_all_mc_signal_endcap_other.root $1_all_mc_signal_endcap_WW.root $1_all_mc_signal_endcap_WZ.root $1_all_mc_signal_endcap_ZZ.root $1_all_mc_signal_endcap_ST_*.root $1_all_mc_signal_endcap_TTG.root $1_all_mc_signal_endcap_ZG.root
hadd -f $1_all_mc_control_barrel_other.root $1_all_mc_control_barrel_WW.root $1_all_mc_control_barrel_WZ.root $1_all_mc_control_barrel_ZZ.root $1_all_mc_control_barrel_ST_*.root $1_all_mc_control_barrel_TTG.root $1_all_mc_control_barrel_ZG.root
hadd -f $1_all_mc_control_endcap_other.root $1_all_mc_control_endcap_WW.root $1_all_mc_control_endcap_WZ.root $1_all_mc_control_endcap_ZZ.root $1_all_mc_control_endcap_ST_*.root $1_all_mc_control_endcap_TTG.root $1_all_mc_control_endcap_ZG.root

#hadd -f $1_all_mc_signal_barrel_other.root $1_all_mc_signal_barrel_WGJJ_interference.root $1_all_mc_signal_barrel_WW.root $1_all_mc_signal_barrel_WZ.root $1_all_mc_signal_barrel_ZZ.root $1_all_mc_signal_barrel_ST_*.root $1_all_mc_signal_barrel_TTG.root $1_all_mc_signal_barrel_ZG.root
#hadd -f $1_all_mc_signal_endcap_other.root $1_all_mc_signal_endcap_WGJJ_interference.root $1_all_mc_signal_endcap_WW.root $1_all_mc_signal_endcap_WZ.root $1_all_mc_signal_endcap_ZZ.root $1_all_mc_signal_endcap_ST_*.root $1_all_mc_signal_endcap_TTG.root $1_all_mc_signal_endcap_ZG.root
#hadd -f $1_all_mc_control_barrel_other.root $1_all_mc_control_barrel_WGJJ_interference.root $1_all_mc_control_barrel_WW.root $1_all_mc_control_barrel_WZ.root $1_all_mc_control_barrel_ZZ.root $1_all_mc_control_barrel_ST_*.root $1_all_mc_control_barrel_TTG.root $1_all_mc_control_barrel_ZG.root
#hadd -f $1_all_mc_control_endcap_other.root $1_all_mc_control_endcap_WGJJ_interference.root $1_all_mc_control_endcap_WW.root $1_all_mc_control_endcap_WZ.root $1_all_mc_control_endcap_ZZ.root $1_all_mc_control_endcap_ST_*.root $1_all_mc_control_endcap_TTG.root $1_all_mc_control_endcap_ZG.root
