make_datacard_unfold.py $1 $2_ewk signal barrel $3 all
make_datacard_unfold.py $1 $2_ewk signal endcap $3 all
make_datacard_unfold.py $1 $2_ewk control barrel $3 all
make_datacard_unfold.py $1 $2_ewk control endcap $3 all
make_datacard_unfold_qcd_ewk.py $1 $2_qcd_ewk signal barrel $3 all
make_datacard_unfold_qcd_ewk.py $1 $2_qcd_ewk signal endcap $3 all
make_datacard_unfold_qcd_ewk.py $1 $2_qcd_ewk control barrel $3 all
make_datacard_unfold_qcd_ewk.py $1 $2_qcd_ewk control endcap $3 all
#make_datacard_unfold.py $1 $2 signal barrel $3 muon
#make_datacard_unfold.py $1 $2 signal endcap $3 muon
#make_datacard_unfold.py $1 $2 signal barrel $3 electron
#make_datacard_unfold.py $1 $2 signal endcap $3 electron
#make_datacard_unfold.py $1 $2 control barrel $3 muon
#make_datacard_unfold.py $1 $2 control endcap $3 muon
#make_datacard_unfold.py $1 $2 control barrel $3 electron
#make_datacard_unfold.py $1 $2 control endcap $3 electron
